sbezverk/nftableslib

nfruleslist.go
Lock root element when incrementing counter id.
=> Fix locking

go.mod, go.sum, mock/mock.go, nfrules.go, nfruleslist.go, nfruleslist_test.go, nftables.go
This PR adds a new api call to get and update a programmed by the kernel rule.
=> Add api call to get and update rule's handle

mock/mock_test.go, nfrules.go
=> Add rule Insert func

nfrules.go
=> Add immediate calls for Create rule and Insert rule

go.mod, nfrules.go
=> Fix return code

nftables.go
=> Add func to detect if nf_tables modulke is loaded

nftables.go
=> remove not needed  parameter

README.md
=> reflect api chance in readme

nfexpressions.go, nfrule_l3.go, nfrules.go
=> multiple fixes and enhancements

README.md, nfrules.go
=> Update README for logging

README.md, nfrule_l3.go
=> Cleanup leftovers

go.mod, go.sum, mock/mock.go, nfchains.go, nfrule_l3.go, nfrules.go, nftables.go, nftables_conn_api.go, nftables_test.go
This PR adds initial support to load already defined on the host nf tables/chains/rules.
=> List tables and Sync functionality

e2e/go.mod, e2e/go.sum, e2e/main.go, e2e/setenv/go.mod, e2e/setenv/go.sum, e2e/setenv/setenv.go, go.mod
=> Initial code for e2e tests

e2e/go.sum, e2e/setenv/go.mod, e2e/setenv/go.sum, e2e/setenv/setenv.go
=> Add code to create veth and ip addresses

e2e/go.sum, e2e/setenv/go.mod, e2e/setenv/go.sum, e2e/setenv/setenv.go
=> Add connectivity test between 2 namespaces

go.mod, go.sum, nfchains.go
Addressing breaking change in google's nftables package
=> Nftables update

cmd/e2e/e2e.go, pkg/e2e/validations/validations.go
=> Adding IPv6 UDP test

go.mod, go.sum
=> pickup updates in nftables package

nfchains.go
=> Add getting list of chains

go.mod, go.sum, mock/mock_test.go, nfconcatrule.go, nfrules.go, nfsets.go
Adding support for `concat` conditions
=> Composed set

nfconcatrule.go
=> Fix dreg value for ipv6 case

nfconcatrule.go, nfsets.go
=> Add support for more than 2 elements in concat

go.mod, go.sum, nfchains.go, nftables.go, nftables_test.go
Optimize error handling for table and chain and update dependencies
=> Error refactor

nfchains.go, nfrules.go
=> Add retry when chain gets deleted if netlink returns  EBUSY

mock/mock.go, nfexpressions.go, nfrules.go, nftables_conn_api.go
=> Start using new AddRule and InsertRule func from nftables

nfrules.go
=> Refactor userdata, simplification

nftables.go, nftables_test.go
=> Cleanup Exist api

go.mod, go.sum, mock/mock.go, nfexpressions.go, nfrule_l3.go, nfrule_l4.go, nfrules.go, nfsets.go, nftables_conn_api.go
Add counter and bunch of other small fixes exposed during testing nfproxy
=> Add counter

go.mod, go.sum, nfconn.go, nftables.go
Move Connection related funcs from nftables code.
=> Conn update

go.mod, go.sum, nfsets.go
=> Add timeout to Set

nfrule_matchact.go, nfrules.go
=> Add MatchAct rule

nfrules.go
=> Add support for rule's comment

nfrules.go
=> Fix rule's comment max length

nfconcatrule.go, nfrules.go, nfsets.go
=> Fix calculation of key's length and ip6addr processing

README.md
Hi,
just wanted to look at example and realized - it can look better.
Cool project, thank you for great work!
=> Just visual changes for README.md

go.mod, go.sum
=> Pickup latest nftables

nfexpressions.go, nfrules.go
This allows setting and checking only parts od packet mark based on bit-wise mask
=> Allow bitmask operations with mark
